server:
  port: 8320
spring:
  profiles:
    active: dev
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rhb_cms_admin?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: "123"
  redis:
    database: 0
    host: 127.0.0.1
    port: 16379
    password: ALARM
  output:
    ansi:
      #检测输出环境是否支持彩色，支持则输出彩色
      enabled: detect
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
mqtt:
  host: tcp://broker.emqx.io:1883
  clientId: shen_mqttx_0d3a698vk
  sendToicPrefix: shenisduyf3_topic/
#logging:
#  config: classpath:log4j2.xml
